import { readFileSync, statSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { businessInitials, buttonTextColor, contrastRatio, customerThemes, defaultCustomerBenefits, resolveCustomerBenefits, visitStars } from "../src/lib/customer-theme";
import { businessPresets, businessTypes, customerThemeColors } from "../src/lib/business-presets";
import { businessUpdateSchema } from "../src/lib/validation";

const root=process.cwd(), source=(path:string)=>readFileSync(join(root,path),"utf8");
const formSource=source("src/components/CheckInForm.tsx"), styles=source("src/components/check-in.css"), fonts=source("src/components/CustomerCapture.astro"), realRoute=source("src/pages/b/[slug].astro"), demoRoute=source("src/pages/demo/capture.astro"), adminPage=source("src/pages/admin/[id].astro");
const validUpdate={displayName:"Café Luna",legalName:"",slug:"cafe-luna",logoUrl:"",privacyUrl:"/privacy",contactPhone:"",contactEmail:"",primaryColor:"#155EEF",secondaryColor:"#0B1220",timezone:"America/New_York",defaultCountry:"US",inactivityDays:"45",offerInactive:"",offerBirthday:"",offerFrequent:"",offerNew:"",googleReviewUrl:"",instagramUrl:"https://www.instagram.com/cafe.luna",businessType:"cafe",theme:"calido",tagline:"Café de barrio",benefit1:"Ofertas para clientes",benefit2:"Sorpresas en tu cumpleaños",benefit3:"Te reconocemos al volver",heroImageUrl:"https://example.com/hero.jpg"};

describe("customer-facing brand styles v2",()=>{
  it("defines four themes, fallback benefits and initials",()=>{expect(customerThemes).toEqual(["elegante","calido","moderno","colorido"]);expect(resolveCustomerBenefits(null)).toEqual(defaultCustomerBenefits);expect(businessInitials("  Café Luna ")).toBe("CL");});
  it("defines eight presets with three valid local photos",()=>{expect(businessTypes).toHaveLength(8);for(const type of businessTypes){const preset=businessPresets[type];expect(preset.benefits).toHaveLength(3);expect(preset.photos).toHaveLength(3);expect(customerThemeColors[preset.theme]).toHaveLength(4);for(const photo of preset.photos){expect(photo).toMatch(new RegExp(`^/stock/${type}/[a-z0-9-]+\\.webp$`));const file=join(root,"public",photo);expect(statSync(file).size).toBeLessThan(200_000);}}});
  it("chooses button labels with WCAG contrast of at least 4.5 to 1",()=>{for(const colors of Object.values(customerThemeColors))for(const color of colors)expect(contrastRatio(color,buttonTextColor(color))).toBeGreaterThanOrEqual(4.5);});
  it("validates type, Instagram and HTTPS or local hero image",()=>{expect(businessUpdateSchema.safeParse(validUpdate).success).toBe(true);expect(businessUpdateSchema.safeParse({...validUpdate,heroImageUrl:"/stock/cafe/cafe-1.webp"}).success).toBe(true);for(const update of [{theme:"otro"},{businessType:"hotel"},{heroImageUrl:"http://example.com/x.jpg"},{heroImageUrl:"/stock/cafe/../secret.webp"},{instagramUrl:"https://instagram.com/cafe"},{instagramUrl:"https://www.instagram.com/cafe-luna"}])expect(businessUpdateSchema.safeParse({...validUpdate,...update}).success).toBe(false);});
  it.each([[1,1],[3,3],[5,5],[9,5]])("fills stars for visit count %i",(count,filled)=>expect(visitStars(count).filter(Boolean)).toHaveLength(filled));
  it("keeps the exact legal copy and WhatsApp unchecked",()=>{expect(formSource).toContain("Tengo 13 años o más.");expect(formSource).toContain("Déjanos tu fecha de cumpleaños y podremos sorprenderte con descuentos, regalos o beneficios especiales en tu día.");expect(formSource).toContain("Recibe ofertas y sorpresas de cumpleaños de {businessName} por WhatsApp. Puedes pedir que paren cuando quieras.");expect(formSource).toContain('name="whatsappOptIn" type="checkbox"');});
  it("renders visit count without reward claims and conditional social links",()=>{expect(formSource).toContain("Esta es tu visita número {success.visitCount}");expect(formSource).not.toMatch(/recompensa|premio|acumula/i);expect(formSource).toContain("googleReviewUrl&&");expect(formSource).toContain("instagramUrl&&");expect(formSource).toContain("Seguir en Instagram");});
  it("uses a priority hero, inline icons and an icon fallback",()=>{expect(formSource).toMatch(/className="hero-image"[^>]*width="1200" height="900"[^>]*fetchPriority="high"/);expect(formSource).toContain('<b>{initials}</b><Icon name={businessType??"store"}/>');expect(formSource).toContain("aria-label={`Marca de ${businessName}`}");expect(formSource).toContain("<svg");});
  it("self-hosts theme fonts and keeps visible focus and reduced motion",()=>{expect(fonts).toContain("fontCss[props.theme]");expect(fonts).not.toContain("fonts.googleapis.com");expect(styles).toContain(":focus-visible");expect(styles).toContain("prefers-reduced-motion");expect(styles).toContain("margin-top:-28px");});
  it("shares capture UI across live and demo routes",()=>{expect(realRoute).toContain('import CustomerCapture from "../../components/CustomerCapture.astro"');expect(demoRoute).toContain('import CustomerCapture from "../../components/CustomerCapture.astro"');expect(demoRoute).toContain("businessPresets");});
  it("exposes every v2 business field in admin",()=>{for(const name of ["businessType","theme","tagline","heroImageUrl","benefit1","benefit2","benefit3","instagramUrl"])expect(adminPage).toContain(`name="${name}"`);expect(adminPage).toContain("data-photo-type");expect(adminPage).toContain("data-color-theme");});
});
